name: protein_benchmark_env
channels:
  - conda-forge
  - rapidsai
dependencies:
  - python=3.12
  - matplotlib
  - pandas
  - ipykernel
  - polars
  - pip
  - numpy
  - biopython
  - scipy
  - cudf
  - pip:
      - scikit-learn
      - seaborn
      - jupyterlab
      - pymol
      - dockq
      - matplotlib
      - pyyaml
